[33md86e4ee[m[33m ([m[1;36mHEAD[m[33m -> [m[1;32mfeature/complete-implementation[m[33m, [m[1;31morigin/feature/complete-implementation[m[33m)[m fix: add missing service property and default values in serverless.yml
[33m9e2cc79[m Complete implementation: Playwright tests + GitHub Actions + detailed response
[33m1ff6102[m[33m ([m[1;31morigin/main[m[33m, [m[1;31morigin/HEAD[m[33m, [m[1;32mmain[m[33m)[m ref: Update README.md
[33mca745de[m ref: flight booking automation project v0.1
[33ma127a05[m feat: initialize flight booking automation project
[33me70d781[m Initial commit
